services:
  backend:
    build: .
    container_name: secret-santa-backend
    restart: unless-stopped
    networks:
      - postgres
      - secret_santa
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '0.33'
          memory: 166M

  frontend:
    build: ./frontend/
    container_name: secret-santa-frontend
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - secret_santa
    deploy:
      resources:
        limits:
          cpus: '0.33'
          memory: 166M

networks:
  postgres:
      name: postgres
      external: true
  secret_santa: