version: '3'

services:
  database:
    container_name: secret_santa_mongodb
    image: mongo:6.0.5
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=secret_santa
      - MONGO_DATA_DIR=/data/db
    volumes:
      - /home/lmello/secret_santa/mongodb/:/data/db
    restart: unless-stopped
    networks:
      - default

  backend:
    container_name: secret_santa_backend
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - default

networks:
  default:
    driver: bridge